### ISSUE TITLE
General roadmap

### ISSUE THREAD

**Issue by yelluw** [yelluw/Bootparts#1]
- [x] Develop initial collection of components in separate branches for each.

- [x] Merge components into master.

- [x] Build  3  intial sample pages.

- [x] Build project website using components.

- [x] Write documentation and use components to showcase them.

- [x] Publish project website.

- [x] Publish documentation.
